name: ottis_pet
description: Ottis Pet é um aplicativo de adoção de animais

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^3.26.0
  splashscreen: ^1.3.5
  google_fonts: ^2.0.0
  introduction_screen: ^2.0.0
  intl: ^0.17.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/